# Файл конфигурации рабочего процесса для GitHub Actions

# Определяем условия запуска сборки
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Скачиваем исходники
      - uses: actions/checkout@v2

      # Устанавливаем необходимые инструменты
      - name: Установка Qt 6.7
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.7.0
          arch: "win64_msvc2019_64"

      - name: Установка MinGW
        run: |
          choco install mingw
          echo "C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin" >> $env:GITHUB_PATH
      - name: Настройка переменных среды
        run: |
          echo "PATH=$PATH:$HOME/.local/bin" >> $GITHUB_ENV
      # Сборка приложения
      - name: Сборка приложения
        run: qmake

      # Публикация результатов сборки
      - name: Публикация результатов сборки
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
